import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    const allProducts = <Product>[
      Product(
        category: Category.accessories,
        id: 0,
        isFeatured: true,
        name: 'Buku Tulis Catatan Bergaris Ruled Notebook Joyko NB-707 A5',
        price: 15000,
        assetName: 'assets/foto/gambar 1.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 1,
        isFeatured: true,
        name:
            'Buku Nota Kontan merk PAPERLINE ukuran 108 x 155 mm Nota 1 ply 2 ply dan 3 ply',
        price: 7000,
        assetName: 'assets/foto/gambar 2.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 2,
        isFeatured: false,
        name: 'SPIDOL WARNA Warni 1 Set Hexagonal Watercolor pensil pulpen ',
        price: 12000,
        assetName: 'assets/foto/gambar 3.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 3,
        isFeatured: true,
        name: 'CS CRAYON SET WARNA 150 PCS',
        price: 31000,
        assetName: 'assets/foto/gambar 4.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 4,
        isFeatured: false,
        name: 'Amplop merk MERPATI Putih Polos isi 100 ',
        price: 10000,
        assetName: 'assets/foto/gambar 5.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 5,
        isFeatured: false,
        name: 'Penggaris merk BUTTERFLY Mistar ukuran 15 sampai 50 cm',
        price: 3000,
        assetName: 'assets/foto/gambar 6.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 6,
        isFeatured: false,
        name: 'Gunting ALLIGATOR',
        price: 10000,
        assetName: 'assets/foto/gambar 7.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 7,
        isFeatured: true,
        name: 'Kaos Kaki Sekolah SD SMP SMA',
        price: 3000,
        assetName: 'assets/foto/gambar 8.jpg',
      ),
      Product(
        category: Category.accessories,
        id: 8,
        isFeatured: true,
        name: 'Stapler merk KENKO 3 ',
        price: 12000,
        assetName: 'assets/foto/gambar 9.jpg',
      ),
      Product(
        category: Category.home,
        id: 9,
        isFeatured: true,
        name: 'Lem cair liquid glue merek ALLIGATOR ',
        price: 4000,
        assetName: 'assets/foto/gambar 10.jpg',
      ),
      Product(
        category: Category.home,
        id: 10,
        isFeatured: false,
        name: 'Lem Fox Kuning Lem Fox Kayu Lem Kertas ukuran 70gr',
        price: 5000,
        assetName: 'assets/foto/gambar 23.jpg',
      ),
      Product(
        category: Category.home,
        id: 11,
        isFeatured: false,
        name: 'Correction Tape Joyko CT-522PTL Pastel ',
        price: 6300,
        assetName: 'assets/foto/gambar 12.jpg',
      ),
      Product(
        category: Category.home,
        id: 12,
        isFeatured: false,
        name:
            '[1PCS] STAPLES NO.10-1M KENKO / ISI KLIP NO 10 KENKO / ISI HEKTER NO.10',
        price: 3000,
        assetName: 'assets/foto/gambar 13.jpg',
      ),
      Product(
        category: Category.home,
        id: 13,
        isFeatured: true,
        name: 'Penghapus Papan Tulis Putih Joyko WE-3 Magnet Whiteboard ',
        price: 7000,
        assetName: 'assets/foto/gambar 14.jpg',
      ),
      Product(
        category: Category.home,
        id: 14,
        isFeatured: true,
        name: 'STICKY NOTE / MEMO STICK / KERTAS MEMO JOYKO 7.5X7.5 CM MMS-30',
        price: 4650,
        assetName: 'assets/foto/gambar 15.jpg',
      ),
      Product(
        category: Category.home,
        id: 15,
        isFeatured: true,
        name: 'PAPER CLIP WARNA C-3100 JOYKO',
        price: 5500,
        assetName: 'assets/foto/gambar 16.jpg',
      ),
      Product(
        category: Category.home,
        id: 16,
        isFeatured: true,
        name: '[ 1 PC ] MINI CUTTER CUTIE BIRD CX-101P',
        price: 3500,
        assetName: 'assets/foto/gambar 17.jpg',
      ),
      Product(
        category: Category.home,
        id: 17,
        isFeatured: false,
        name: '[ 1 PC ] SPIDOL PAPAN TULIS / WHITEBOARD JOYKO WM-70',
        price: 12200,
        assetName: 'assets/foto/gambar 18.jpg',
      ),
      Product(
        category: Category.home,
        id: 18,
        isFeatured: true,
        name: 'Refill Tinta Spidol White Board Snowman WBI-20',
        price: 13500,
        assetName: 'assets/foto/gambar 19.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 19,
        isFeatured: false,
        name: 'Rak buku anak - Rak buku minimalir',
        price: 32500,
        assetName: 'assets/foto/gambar 20.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 20,
        isFeatured: false,
        name: 'Tempat HP di dinding',
        price: 13000,
        assetName: 'assets/foto/gambar 21.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 21,
        isFeatured: false,
        name: 'Sticker Label Panda',
        price: 1200,
        assetName: 'assets/foto/gambar 22.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 22,
        isFeatured: false,
        name: 'Kertas HVS SiDU Fotocopy 75 gsm A4',
        price: 50000,
        assetName: 'assets/foto/gambar 23.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 23,
        isFeatured: false,
        name: 'Kertas HVS SiDU Fotocopy 75 gsm A4',
        price: 48000,
        assetName: 'assets/foto/gambar 38.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 24,
        isFeatured: true,
        name: 'Name Tag ID Card Holder',
        price: 4500,
        assetName: 'assets/foto/gambar 24.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 25,
        isFeatured: false,
        name: 'Case ID Card + Tali Kulit Sintetis ',
        price: 5500,
        assetName: 'assets/foto/gambar 25.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 26,
        isFeatured: false,
        name: 'Tali ID Card 2cm ',
        price: 2500,
        assetName: 'assets/foto/gambar 26.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 27,
        isFeatured: true,
        name: 'Penghapus Joyko 526-B20 ',
        price: 4500,
        assetName: 'assets/foto/gambar 27.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 28,
        isFeatured: true,
        name: 'Jam Meja Model Sepeda',
        price: 27000,
        assetName: 'assets/foto/gambar 28.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 29,
        isFeatured: true,
        name: 'tempat pensil bulu warna pelangi ',
        price: 21000,
        assetName: 'assets/foto/gambar 29.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 30,
        isFeatured: true,
        name: 'Loose Leaf Joyko A5 50 Ruled',
        price: 11000,
        assetName: 'assets/foto/gambar 30.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 31,
        isFeatured: false,
        name: 'KARTON PLANO PINDO DELI TEBAL',
        price: 5000,
        assetName: 'assets/foto/gambar 31.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 32,
        isFeatured: false,
        name: 'Cellophane COQUETTE RIBBON',
        price: 7500,
        assetName: 'assets/foto/gambar 32.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 33,
        isFeatured: true,
        name: 'Pencil Pensil P-8156 ',
        price: 13000,
        assetName: 'assets/foto/gambar 33.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 34,
        isFeatured: false,
        name: 'Pensil 2B Joyko 6161 12pcs',
        price: 3000,
        assetName: 'assets/foto/gambar 34.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 35,
        isFeatured: false,
        name: 'Watercolor Cake Combo 12 Warna ',
        price: 24,
        assetName: 'assets/foto/gambar 35.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 36,
        isFeatured: false,
        name: 'Tas Tote Bag Wanita Tokyo',
        price: 35000,
        assetName: 'assets/foto/gambar 36.jpg',
      ),
      Product(
        category: Category.clothing,
        id: 37,
        isFeatured: true,
        name: 'Kalkulator Citizen SLD-888',
        price: 45000,
        assetName: 'assets/foto/gambar 37.jpg',
      ),
    ];
    if (category == Category.all) {
      return allProducts;
    } else {
      return allProducts.where((Product p) {
        return p.category == category;
      }).toList();
    }
  }
}
